-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  rating INTEGER NOT NULL,
  description TEXT default 'Description',
  url TEXT NOT NULL
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, rating, description, url)
values
  ('Google', '5', 'Find everything you cant find elsewhere', 'www.google.com'),
  ('Thinkful', '5', 'Learn...anything', 'www.thinkful.com'),
  ('YouTube', '3', 'People attacked by poisonous snakes!', 'www.youtube.com'),
  ('Foo', '2', 'Foo is as foo does', 'www.foo.com'),
  ('Bar', '4', 'Can I BAR-O a cup of sugar', 'www.bar.com'),
  ('Facenook', '1', 'All of the phoniest facts you ever thunk', 'www.blahblahblah.com'),
  ('LinkedIn', '5', 'Get connected, get a job, get a clue', 'www.linkedin.com'),
  ('ThreeMoreRows', '3', '', 'www.threemorerows.com'),
  ('TwoMoreRows', '2', '', 'www.twomorerows.com'),
  ('Wooooo', '5', 'I did it!!!', 'www.woooo.com');